version: '3'
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: frontend-reactjs-app
    restart: unless-stopped
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - room-net
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
  backend: 
    stdin_open: true
    tty: true
    container_name: backend-express-app 
    restart: unless-stopped
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - room-net
    volumes:
      - ./proxy:/app
      - /app/node_modules
  nginx:
    container_name: nginx
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - room-net
networks:
    room-net: